- hosts: production 
  remote_user: user
  vars:
    app_name: riskinfo_lk
    github_user: riskinfo-lk
    server_name: 192.168.10.50
    deploy_user: user 
  roles:
     - { role: ortelius.geonode }
